### ISSUE TITLE
arcstone converter line 47

### ISSUE THREAD

**Issue by xackery** [daeken/OpenEQ#24]
D:\code\eqemu\openeq\converter>c:\Python27\python.exe converter.py arcstone
Traceback (most recent call last):
  File "converter.py", line 64, in <module>
    main(*sys.argv[1:])
  File "converter.py", line 56, in main
    convertNew(name)
  File "converter.py", line 47, in convertNew
    readZon(file('eqdata/%s.zon' % name, 'rb').read(), zone, zfiles)
IOError: [Errno 2] No such file or directory: 'eqdata/arcstone.zon'

**Comment by xackery** [comment]
Similar to #21
