### ISSUE TITLE
barren converter (line 47)

### ISSUE THREAD

**Issue by xackery** [daeken/OpenEQ#28]
Traceback (most recent call last):
  File "converter.py", line 64, in <module>
    main(*sys.argv[1:])
  File "converter.py", line 56, in main
    convertNew(name)
  File "converter.py", line 47, in convertNew
    readZon(file('eqdata/%s.zon' % name, 'rb').read(), zone, zfiles)
IOError: [Errno 2] No such file or directory: 'eqdata/barren.zon'

**Comment by xackery** [comment]
similar to #21
