### ISSUE TITLE
broodlands converter (line 44)

### ISSUE THREAD

**Issue by xackery** [daeken/OpenEQ#31]
D:\code\eqemu\openeq\converter>c:\Python27\python.exe converter.py broodlands
Traceback (most recent call last):
  File "converter.py", line 64, in <module>
    main(*sys.argv[1:])
  File "converter.py", line 56, in main
    convertNew(name)
  File "converter.py", line 45, in convertNew
    readZon(zfiles['%s.zon' % name], zone, zfiles)
  File "D:\code\eqemu\openeq\converter\zon.py", line 23, in readZon
    readTer(s3d[fn], zone, s3d)
  File "D:\code\eqemu\openeq\converter\ter.py", line 44, in readTer
    assert (version == 3 or b.uint() == 0) and b.pos == len(b)
AssertionError

**Comment by xackery** [comment]
similar to #29
