### ISSUE TITLE
corathus, corathusb converter (line 50)

### ISSUE THREAD

**Issue by xackery** [daeken/OpenEQ#38]
Traceback (most recent call last):
  File "converter.py", line 64, in <module>
    main(*sys.argv[1:])
  File "converter.py", line 56, in main
    convertNew(name)
  File "converter.py", line 47, in convertNew
    readZon(file('eqdata/%s.zon' % name, 'rb').read(), zone, zfiles)
  File "D:\code\eqemu\openeq\converter\zon.py", line 23, in readZon
    readTer(s3d[fn], zone, s3d)
  File "D:\code\eqemu\openeq\converter\ter.py", line 50, in readTer
    zmats[index] = Material(FLAG_NORMAL if visible else FLAG_TRANSPARENT, [s3d[props['e_TextureDiffuse0'].lower()]] if visible else [])
KeyError: 'grid_standard.dds'

**Comment by xackery** [comment]
#25 similar
