### ISSUE TITLE
crystallos converter (line 47)

### ISSUE THREAD

**Issue by xackery** [daeken/OpenEQ#42]
reading mod obp_newlightbeama.mod
Traceback (most recent call last):
  File "converter.py", line 64, in <module>
    main(*sys.argv[1:])
  File "converter.py", line 56, in main
    convertNew(name)
  File "converter.py", line 48, in convertNew
    zone.output(zip)
  File "D:\code\eqemu\openeq\converter\zonefile.py", line 142, in output
    self.coalesceObjectMeshes()
  File "D:\code\eqemu\openeq\converter\zonefile.py", line 138, in coalesceObjectMeshes
    gmesh = reduce(lambda a, b: a.add(b), meshlist)
  File "D:\code\eqemu\openeq\converter\zonefile.py", line 138, in <lambda>
    gmesh = reduce(lambda a, b: a.add(b), meshlist)
  File "D:\code\eqemu\openeq\converter\zonefile.py", line 47, in add
    self.vertbuffer.data += mesh.vertbuffer.data
MemoryError

**Comment by xackery** [comment]
#21
